-- Database untuk TVRI Equipment Management System
-- Dibuat untuk XAMPP/phpMyAdmin

CREATE DATABASE IF NOT EXISTS `tvri_equipment` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `tvri_equipment`;

-- Tabel Equipment (Alat)
CREATE TABLE `equipment` (
  `id` varchar(36) NOT NULL,
  `serial_number` text NOT NULL,
  `name` text NOT NULL,
  `type` text NOT NULL,
  `condition` text NOT NULL,
  `notes` text DEFAULT '',
  `status` text NOT NULL DEFAULT 'available',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabel Borrowings (Peminjaman)
CREATE TABLE `borrowings` (
  `id` varchar(36) NOT NULL,
  `borrower_name` text NOT NULL,
  `borrower_email` text,
  `equipment_id` varchar(36) NOT NULL,
  `event_name` text NOT NULL,
  `pickup_date` text NOT NULL,
  `pickup_time` text NOT NULL,
  `expected_return_date` text NOT NULL,
  `expected_return_time` text NOT NULL,
  `actual_return_date` text,
  `actual_return_time` text,
  `borrow_condition` text NOT NULL,
  `return_condition` text,
  `notes` text DEFAULT '',
  `return_notes` text DEFAULT '',
  `status` text NOT NULL DEFAULT 'active',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `equipment_id` (`equipment_id`),
  CONSTRAINT `borrowings_ibfk_1` FOREIGN KEY (`equipment_id`) REFERENCES `equipment` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabel Users (untuk sistem login jika diperlukan)
CREATE TABLE `users` (
  `id` varchar(36) NOT NULL,
  `username` text NOT NULL,
  `password` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert data equipment dari list TVRI World
INSERT INTO `equipment` (`id`, `serial_number`, `name`, `type`, `condition`, `notes`, `status`) VALUES
(UUID(), 'S/N', 'Camera Canon XF605 1', 'ENG Camera', 'Butuh Perbaikan', 'Hood Lepas', 'maintenance'),
(UUID(), '283679500117', 'Camera Canon XF605 2', 'ENG Camera', 'Baik', '', 'available'),
(UUID(), '283679500141', 'Camera Canon XF605 3', 'ENG Camera', 'Baik', '', 'available'),
(UUID(), 'A9TRA0004', 'Panasonic P2HD 1', 'ENG Camera', 'Baik', '', 'available'),
(UUID(), 'G8TCA0025', 'Panasonic P2HD 2', 'ENG Camera', 'Butuh Perbaikan', 'Hood Lepas', 'maintenance'),
(UUID(), 'K5TDA0056', 'Panasonic AG-AC', 'ENG Camera', 'Baik', '', 'available'),
(UUID(), '5092000530', 'Mic 2 Sennheizer SKM 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '', 'Reciever Mic 2 EK 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5052000525', 'Mic 1 Sennheizer SKM 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5122004956', 'Reciever Mic 1 EK 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5373000854', 'Mic 3 Sennheizer SKM 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), 'SN Buram', 'Reciever Mic 3 EK 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5431006515', 'Mic 4 Sennheizer SKM 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5451077772', 'Reciever Mic 4 EK 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5451006712', 'Mic 5 Sennheizer SKM 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '5431076357', 'Reciever Mic 5 EK 100 G4', 'Microphone', 'Baik', '', 'available'),
(UUID(), '4358000111', 'Mic 6 Sennheizer SKM 100 G4', 'Microphone', 'Rusak', '', 'damaged'),
(UUID(), '45188000899', 'Reciever Mic 6 EK 100 G4', 'Microphone', 'Rusak', '', 'damaged'),
(UUID(), '20H00066488', 'Godox LF308 Bi 1', 'Lighting', 'Baik', '', 'available'),
(UUID(), '20H00066387', 'Godox LF308 Bi 2', 'Lighting', 'Baik', '', 'available'),
(UUID(), '20H00066490', 'Godox LF308 Bi 3', 'Lighting', 'Baik', '', 'available'),
(UUID(), '6BU04D88736', 'Aputure Amaran FI', 'Lighting', 'Baik', '', 'available'),
(UUID(), 'LUM-F970-BTR', 'Lition Baterai 1', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'LUM-F970-BTR', 'Lition Baterai 2', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'LUM-F970-BTR', 'Lition Baterai 3', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'LUM-F970-BTR', 'Lition Baterai 4', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'LUM-F970-BTR', 'Lition Baterai 5', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 1', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 2', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 3', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 4', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 5', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'BP-A30', 'Baterai Canon 6', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'AG-VBR59', 'Baterai Panasonic P2', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'AG-VBR59', 'Baterai Panasonic P2', 'Baterai', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Kingma Li-ion', 'Baterai', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Kingma Li-ion', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'VW-VBG6', 'Baterai Panasonic AG-AC', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'VW-VBG6', 'Baterai Panasonic AG-AC', 'Baterai', 'Baik', '', 'available'),
(UUID(), 'CG-A20', 'Charger Baterai Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'CG-A20', 'Charger Baterai Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'CG-A20', 'Charger Baterai Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'DE-A88D', 'Charger Baterai Panasonic', 'Charger', 'Baik', '', 'available'),
(UUID(), 'BM045-f550', 'Charger Baterai Li-Ion KingMa', 'Charger', 'Baik', '', 'available'),
(UUID(), 'K48V120400G', 'AC Adapter KPTEC', 'Charger', 'Baik', '', 'available'),
(UUID(), 'K48V120400G', 'AC Adapter KPTEC', 'Charger', 'Baik', '', 'available'),
(UUID(), 'K48V120400G', 'AC Adapter KPTEC', 'Charger', 'Baik', '', 'available'),
(UUID(), 'CA-CP200L', 'AC Adapter Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'CA-CP200L', 'AC Adapter Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'CA-CP200L', 'AC Adapter Canon', 'Charger', 'Baik', '', 'available'),
(UUID(), 'VW-AD20E', 'Charger Baterai AG-AC', 'Charger', 'Baik', '', 'available'),
(UUID(), '3S2312-41512', 'Liveu LU300S', '3G Bounding', 'Baik', '', 'available'),
(UUID(), 'MTT606A', 'Milibo 1', 'Tripod', 'Rusak', 'Kaki Tripod Tidak Bisa di Ajust', 'damaged'),
(UUID(), 'MTT606A', 'Milibo 2', 'Tripod', 'Baik', '', 'available'),
(UUID(), 'MTT606A', 'Milibo 3', 'Tripod', 'Baik', '', 'available'),
(UUID(), '', 'Milbo Besar 1', 'Tripod', 'Baik', '', 'available'),
(UUID(), '', 'Milbo Besar 2', 'Tripod', 'Baik', '', 'available'),
(UUID(), 'RT30B', 'Libec LX7 1', 'Tripod', 'Baik', 'Tidak Ada Mounting', 'available'),
(UUID(), 'RT30B', 'Libec LX7 2', 'Tripod', 'Baik', '', 'available'),
(UUID(), 'RT30B', 'Takara', 'Stand Lighting', 'Baik', '', 'available'),
(UUID(), 'RT30B', 'Takara', 'Stand Lighting', 'Baik', '', 'available'),
(UUID(), '', 'Legion 1', 'Laptop', 'Baik', '', 'available'),
(UUID(), '', 'Legion 2', 'Laptop', 'Baik', '', 'available'),
(UUID(), '4474390', 'Sony Alpha A9', 'Camera Mirorles', 'Baik', '', 'available'),
(UUID(), 'SEL70200G', 'Sonny 70-200', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '1828883', 'Sony SEL100400GM', 'Lensa Camera', 'Rusak', '', 'damaged'),
(UUID(), '2026324', 'Sony Sel24-105G', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '1933114', 'Zeiss Sel35F28z', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '', 'Sony FX3', 'Camera Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Sony FX3', 'Camera Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Sony Sel 50 mm f 1.2 GM', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '', 'Sony Sel 16-35 f 2.8 GM', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '', 'Sony Sel 70-200 f 2.8 GM', 'Lensa Camera', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Sony a9', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Sony a9', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Sony a9', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai FX 3', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai FX 3', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai FX 3', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai FX 3', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Kingma Mirorles', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Baterai Kingma Mirorles', 'Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Drone DJI Mavic 3', 'Drone', 'Baik', '', 'available'),
(UUID(), '', 'DJI RS 3', 'Stabilizer Camera', 'Baik', '', 'available'),
(UUID(), '', 'Sony TOUGH 60 GB', 'Memory FX3', 'Baik', '', 'available'),
(UUID(), '', 'Sony TOUGH 60 GB', 'Memory FX3', 'Baik', '', 'available'),
(UUID(), '', 'Card Reader Sony TOUGH', 'Card Reader Sony TOUGH', 'Baik', '', 'available'),
(UUID(), '', 'Charger Sony Mirorless', 'Charger Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'Charger Sony Mirorless', 'Charger Baterai Mirorles', 'Baik', '', 'available'),
(UUID(), '', 'PC Capture', 'Komputer', 'Rusak', 'Rusak / Tidak Bisa Menyala', 'damaged'),
(UUID(), '', 'PC Capture', 'Komputer', 'Rusak', 'Rusak / Tidak Bisa Menyala', 'damaged');